-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggkIgAomQXEiGwIMX
vPcRkISHIiatRtzoZH9sG6EBWJOgCgYIKoZIzj0DAQehRANCAARKesZfQQ7tvoIM
NjvVdK5pU/Rzuob6Y3wkGaQ1TzN1bcXw6GtCQ68jZGpwwTCMa11F0/ukF4TdMUdQ
QTJX9ryV
-----END PRIVATE KEY-----